# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cudo theme
email: dmxbt94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

facebook_username: gyuro
twitter_username: gyuro
github_username: gyuro
google_username: gyuro
linkedin_username: gyuro
behance_username: gyuro
dribble_username: gyuro


# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: #marko
  - title: Blog
    url: #milos
  - title: Contact
    url: #dragan


# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:title
